# Copyright 2023, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

version: "3.5"
services:
  coherence1:
    hostname: server1
    networks:
      coherence:
        aliases:
          - server1
    image: ${DOCKER_REGISTRY}/${COHERENCE_TYPE}:${COHERENCE_VERSION}
    environment:
      - COHERENCE_WKA=server1
    ports:
      - "30000:30000"
      - "1408:1408"
      - "9612:9612"
      - "8080:8080"
      - "6676:6676"
    volumes:
      - .:/args
      - ./cert:/certs

  coherence2:
    hostname: server2
    networks:
      coherence:
        aliases:
          - server2
    image: ${DOCKER_REGISTRY}/${COHERENCE_TYPE}:${COHERENCE_VERSION}
    environment:
      - COHERENCE_WKA=server1
    ports:
      - "9613:9612"
    volumes:
      - .:/args
      - ./cert:/certs

networks:
  coherence: