# Copyright 2020, 2025, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence JavaScript Client GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: JS Client Validation

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches-ignore:
    - ghpages
  pull_request:
    types:
      - opened
    branches:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x, 22.x, 23.x]
        coherence-version: [22.06.11, 14.1.2-0-1, 25.03]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    # install protoc
    - run: curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_64.zip"
    - run: unzip protoc-22.2-linux-x86_64.zip -d /tmp/grpc
    - run: echo "/tmp/grpc/bin" >> $GITHUB_PATH
    # install project deps
    - run: npm install
    # run tests
    - run: COHERENCE_VERSION=${{ matrix.coherence-version }} npm run test-cycle
    # run tests using TLS
    - run: COHERENCE_VERSION=${{ matrix.coherence-version }} npm run test-cycle-tls
    # clean up
    - name: Archive production artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
          name: save-log-file-${{ matrix.node-version }}-${{ matrix.coherence-version }}
          path: logs-*.txt
